# Generated by Django 5.0 on 2024-01-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rango", "0004_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="page",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
