# Generated by Django 5.0 on 2024-01-21 22:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rango", "0006_contactsubmission"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactSubmission",
        ),
    ]
