# Generated by Django 5.0 on 2024-01-23 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rango", "0008_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="datetime_submitted",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
