# Generated by Django 5.0 on 2024-03-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rango", "0012_alter_portfolio_ape_alter_portfolio_btc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="trades",
            field=models.TextField(blank=True, null=True),
        ),
    ]
